/**
 * Centralized registry of all admin audit action strings.
 * These are used in audit log entries created throughout the admin services.
 *
 */
export const AuditAction = {
    // --- Admin Management ---
    UPDATE_ADMIN_ROLE: "UPDATE_ADMIN_ROLE",

    // --- Groups ---
    CREATE_GROUP: "CREATE_GROUP",
    UPDATE_GROUP: "UPDATE_GROUP",
    DELETE_GROUP: "DELETE_GROUP",

    // --- eSIM Plans ---
    CREATE_ESIM_PLAN: "CREATE_ESIM_PLAN",
    UPDATE_ESIM_PLAN: "UPDATE_ESIM_PLAN",
    UPDATE_ESIM_PLAN_PRICING: "UPDATE_ESIM_PLAN_PRICING",
    UPDATE_ESIM_PLAN_AVAILABILITY: "UPDATE_ESIM_PLAN_AVAILABILITY",
    CREATE_ESIM_PLAN_PROMO: "CREATE_ESIM_PLAN_PROMO",

    // --- Fees ---
    UPDATE_ASSET_FEES: "UPDATE_ASSET_FEES",
    UPDATE_SWAP_FEES: "UPDATE_SWAP_FEES",

    // --- Config ---
    UPDATE_REWARDS_CONFIG: "UPDATE_REWARDS_CONFIG",
    UPDATE_REGION_STATUS: "UPDATE_REGION_STATUS",
    UPDATE_CURRENCY_STATUS: "UPDATE_CURRENCY_STATUS",
    UPDATE_LIMITS: "UPDATE_LIMITS",
    UPDATE_REFERRAL_RULES: "UPDATE_REFERRAL_RULES",
    UPDATE_FEATURE_FLAG: "UPDATE_FEATURE_FLAG",
    ENABLE_FEATURE_USERS: "ENABLE_FEATURE_USERS",

    // --- Transactions ---
    REVERSE_TRANSACTION: "REVERSE_TRANSACTION",
    REFUND_TRANSACTION: "REFUND_TRANSACTION",

    // --- Support ---
    DISABLE_USER: "DISABLE_USER",
    ENABLE_USER: "ENABLE_USER",
    CREATE_SUPPORT_TEMPLATE: "CREATE_SUPPORT_TEMPLATE",
    UPDATE_SUPPORT_TEMPLATE: "UPDATE_SUPPORT_TEMPLATE",
    DELETE_SUPPORT_TEMPLATE: "DELETE_SUPPORT_TEMPLATE",

    // --- Roles & Permissions ---
    CREATE_ROLE: "CREATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    ASSIGN_PERMISSION: "ASSIGN_PERMISSION",
    CREATE_PERMISSION: "CREATE_PERMISSION",
    CREATE_PERMISSIONS: "CREATE_PERMISSIONS",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    DELETE_PERMISSION: "DELETE_PERMISSION"
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
